# This is a basic workflow to help you get started with Actions

name: éƒ¨ç½²âš™ï¸

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the feature branch
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: ä½¿ç”¨nodejs
        uses: actions/setup-node@v2-beta
        with:
          node-version: '15'
      - name: å®‰è£…ä¾èµ–
        run: npx pnpm install
      - name: æ‰“åŒ…
        run: CI='' npm run build

      - name: éƒ¨ç½²åˆ°æœåŠ¡å™¨ğŸ’»
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
            SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
            ARGS: "-rltgoDzvO --delete"
            SOURCE: "dist/"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: project/bloc_frontend_dev

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo hoorayï¼éƒ¨ç½²å®ŒæˆğŸ¥³
  # "notify" workflow for slack notification
  notify:
    name: Slacké€šçŸ¥éƒ¨ç½²å®Œæˆ
    runs-on: ubuntu-latest
    # Only run this workflow when "build" workflow succeeds
    needs: [build]
    steps:
      - uses: abinoda/slack-action@master
        env:
          # required
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          # custom message to send to slack
          args: '{\"channel\":\"${{ secrets.SLACK_PR_CHANNEL_ID }}\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*éƒ¨ç½²å®Œæˆ[dev]:* \n ${{ github.event.head_commit.message }}\"}}]}'

      - name: Run a one-line script
        run: echo hoorayï¼å·²å‘é€é€šçŸ¥ğŸº